### ISSUE TITLE
xRegistry cannot change value type

### ISSUE THREAD

**Issue by kinwolfqc** [dsccommunity/xPSDesiredStateConfiguration#436] opened 2018-08-02 17:51 UTC
In our environment, a registry key was wrongly created as a QWord instead of a DWord.  DSC caught this, but it fails to fix it as the Set part does not seem to take this into account?

Here is the part where it detect the wrong value:
>VERBOSE: [POC02]:                            [[Registry]TCPKeepAlive::[DSQ_ConfigNoyau]Noyau] The type of the value KeepAliveTime under the registry key at path HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Tcpip\Parameters does not match the expected type.
Expected DWord but was QWord.

and here is the set part
>VERBOSE: [POC02]:                            [[Registry]TCPKeepAlive::[DSQ_ConfigNoyau]Noyau] Set-TargetResource is starting for Registry resource with Key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Tcpip\Parameters
VERBOSE: [POC02]:                            [[Registry]TCPKeepAlive::[DSQ_ConfigNoyau]Noyau] The registry key at path HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Tcpip\Parameters exists.
VERBOSE: [POC02]:                            [[Registry]TCPKeepAlive::[DSQ_ConfigNoyau]Noyau] The value KeepAliveTime under the registry key at path HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Tcpip\Parameters has already been set to the specified value.
VERBOSE: [POC02]:                            [[Registry]TCPKeepAlive::[DSQ_ConfigNoyau]Noyau] Set-TargetResource has finished for Registry resource with Key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Tcpip\Parameters

As you can see, it says that the value has **"already been set to the specified value"**, so the set part does not seem to verify the Type.

As such, the node is always reported as not in the desired state.

**Comment by johlju** [comment] 2018-08-03 05:40
Thanks for reporting this!

It seems this is tested here in the `Test-TargetResource` function, but it is not tested in the `Set-TargetResource`.

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/1063b2ffc7c3f95a1a3464568e180461cf899217/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L457-L462

The check above seems it could be moved into this helper function that is called by both `Test-TargetResource` and `Set-TargetResource`.

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/1063b2ffc7c3f95a1a3464568e180461cf899217/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1354

With this change, and using the `-Force` parameter, then the helper function `Set-RegistryKeyValue` is called (which looks like it will overwrite the value with the new type).

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/1063b2ffc7c3f95a1a3464568e180461cf899217/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L272-L291

**Comment by johlju** [comment] 2018-08-03 05:48
Labeled this help wanted so that anyone in the community can run with this. This looks like a good issue for someone who wants to learn how to write a (regression) tests for test driven development.

**Comment by albvar** [comment] 2019-05-31 17:57
I was just about to report this exact issue. Noticed issue reported on 8/2018, there must be a huge backlog? Anyhow up-voting this, noticed it with version 8.6.0.0.

**Comment by mhendric** [comment] 2019-06-03 16:59
@albvar , there has indeed been a huge backlog, as well as a lack of volunteers. I don't suppose you want to volunteer to help with this one? :)

**Comment by mkht** [comment] 2019-12-25 13:49
It is a disappointment that those who tackle this issue do not appear for a long time.
Now I am working on this and will create a PR soon.

**Comment by mkht** [comment] 2020-01-11 05:07
This bug has been fixed in PR #658 . Please close this issue.
@johlju @PlagueHO

**Comment by gaelcolas** [comment] 2020-01-11 06:44
Glad it's finally fixed. Thanks for your contribution @mkht !

**Closed by gaelcolas** 2020-01-11 06:44 UTC
Labels: bug, good first issue, help wanted
